language: node_js
node_js:
- "10"

deploy:
  provider: npm
  api_key: $API_TOKEN
  on:
    tags: true

notifications:
  email:
    recipients:
    - info@webish.one
    on_success: change
    on_failure: always